project_id = "wqzseofoerwevfebguse"

[functions.booking-webhook]
verify_jwt = false

[functions.api]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
